---

- name:  "run > finished"
  local_action: >
    command terminal-notifier -sound {{ terminal_notifier_sound }} -title '{{ terminal_notifier_title }}' -message '{{ terminal_notifier_msg }}'
  ignore_errors: yes
  tags:
    - awareness
    - notification
